name: release ci cd

on:
  push:
    branches: [ release]
  pull_request:
    branches: [ release]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test || true  # Currently set to pass even if tests fail
      
    # Optional: Add deployment step here if needed
    # - name: Deploy
    #   if: github.ref == 'refs/heads/main' && matrix.node-version == '20.x'
    #   run: |
    #     # Add deployment commands here
